variables:  
  PoolName: 'Hosted VS2017'
  EnvironmentName: 'ch-0331-03'
jobs:
- deployment: job1
  environment: $(EnvironmentName)
  pool: $(PoolName)
  strategy:
   runOnce:
    deploy:
     steps:
     - script: echo Hello, world!
       displayName: 'Run a one-line script'
